spring.application.name=vehicle-service
server.port=8082

#eureka discovery client 
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

#mongodb 
spring.data.mongodb.uri=mongodb://admin:admin123@localhost:27017
spring.data.mongodb.database=vehicle-service

mqtt.uri=tcp://${MQTT_HOST:localhost}:1883
mqtt.username=admin
mqtt.password=admin


management.endpoints.web.exposure.include=health,info